AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ClusterName:
    Type: String
    Default: helm-contract-test
  ReleaseName:
    Type: String
    Default: helm-contract-test
Resources:
  EKSResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://abcpteb.s3-eu-west-1.amazonaws.com/contract_test_exports.template.yaml'
      Parameters:
        ClusterName: !Ref ClusterName
        ReleaseName: !Ref ReleaseName
